### ISSUE TITLE
Show user name in Chat list

### ISSUE THREAD

**Issue by mohocp** [stfalcon-studio/ChatKit#124] opened 2018-01-05 21:15 UTC
How I Can display user name in chat list ?

**Comment by sourabhz** [comment] 2018-02-18 21:09
You got it done or not.

**Comment by bdykzeul** [comment] 2018-03-18 03:30
yes please! avatars are not always available

**Comment by bevzaanton** [comment] 2018-07-10 13:37
Duplicate of #166

**Closed by bevzaanton** 2018-07-10 13:37 UTC
