### ISSUE TITLE
Avatar is not showing in messages user sends

### ISSUE THREAD

**Issue by freundyotam** [stfalcon-studio/ChatKit#106] opened 2017-10-31 20:02 UTC
I don't why but there is no avatar in the messages the user sends, only receives.
I tried to set the user's avatar to something constant and still nothing.
submitting msg:
```
@Override
public boolean onSubmit(CharSequence input) {
    final ChatMessage newMessage = new ChatMessage(input, senderId , firstName, profileLink, Calendar.getInstance().getTime());
               ...
    adapter.addToStart(newMessage, true);
    Log.e("can", "submit");
    }
});
```

ChatMessage class:
```
public ChatMessage(String message, String senderID, String displayName, String profileLink, Date dateCreated) {
        this.message = message;
        this.senderID = senderID;
        this.displayName = displayName;
        this.profileLink = profileLink;
        this.DateCreated = dateCreated;
    }

   .....
    @Override
    public IUser getUser() {
        return new ChatUser(senderID, displayName, profileLink);
    }
```

ChatUser class:
```
public class ChatUser implements IUser {
  ...
    public ChatUser(String senderId, String displayName, String profileUrl) {
        this.senderId = senderId;
        this.displayName = displayName;
        this.profileUrl = profileUrl;
    }
....
....
    @Override
    public String getAvatar() {
        return "some real working image url";
    }
}
```

And loading with Picasso:
```adapter = new MessagesListAdapter<>(senderId + "", new ImageLoader() {
      @Override
      public void loadImage(final ImageView imageView, final String url) {
       Picasso.with(ChatActivity.this).load(R.drawable.grub_sent_icon).into(imageView);
    }
});
```

Why I don't see my avatar? please help me solve this

**Comment by alouanemed** [comment] 2017-12-03 10:34
duplicate of #54

**Comment by troy379** [comment] 2018-02-19 10:26
Agreed. Closing this one.

**Closed by troy379** 2018-02-19 10:26 UTC
