### ISSUE TITLE
Emoji not recognized in textview of MessageList when sent from google keyboard 

### ISSUE THREAD

**Issue by sourabhz** [stfalcon-studio/ChatKit#161] opened 2018-06-24 16:44 UTC

**Comment by brandon-haugen** [comment] 2018-06-25 19:58
Duplicate request of #121 maybe?

**Comment by bevzaanton** [comment] 2018-07-10 09:06
@brandon-haugen Yes, you are right. Duplicate of #121

**Closed by bevzaanton** 2018-07-10 09:06 UTC
