### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by DanteAndroid** [stfalcon-studio/ChatKit#26] opened 2017-04-24 08:00 UTC
```
java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
```

Code:
```
        MessagesListAdapter<Message> adapter = new MessagesListAdapter<>(fromId, (imageView, url) -> Glide.with(ConversationActivity.this)
                .load(url)
                .into(imageView));
        messagesList.setAdapter(adapter);

        adapter.addToEnd(convert(list), false);


    private List<Message> convert(List<AVIMMessage> list) {
        List<Message> messages = new ArrayList<>();

        Log.d(TAG, "convert: " + list.size());
        for (AVIMMessage m : list) {
            if (m instanceof AVIMTextMessage) {
                AVIMTextMessage text = (AVIMTextMessage) m;
                Message message = new Message();
                message.setText(text.getText());
                message.setCreatedAt(new Date(m.getTimestamp()));
                message.setId(m.getMessageId());
                User u = new User(Integer.parseInt(text.getFrom()));
                message.setAuthor(new Author(u));
                Log.d(TAG, "convert: add message");
                messages.add(message);
            }
        }

        return messages;
    }
```

**Comment by troy379** [comment] 2017-04-28 14:45
Hi @DanteAndroid !
Can you show the full stack trace please?

**Comment by DanteAndroid** [comment] 2017-05-02 01:04
```
  java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
                                                                     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(SourceFile:6368)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:5555)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5440)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5436)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.a(SourceFile:2224)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1551)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1511)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:570)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3583)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3312)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3844)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.support.design.widget.CoordinatorLayout.layoutChild(SourceFile:1167)
                                                                     at android.support.design.widget.CoordinatorLayout.onLayoutChild(SourceFile:852)
                                                                     at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:871)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
                                                                     at android.view.View.layout(View.java:17938)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7403)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
Thx for your reply.
FYI, the `List<Message>` contains only one message.

**Comment by troy379** [comment] 2017-05-03 08:46
what is the version of library you use?
and why are you converting your objects?

**Comment by DanteAndroid** [comment] 2017-05-03 08:48
1. `    compile 'com.github.stfalcon:chatkit:0.2.0'  `
2.  Coz messages I received are AVIMMessage instead of `IMessage`

**Comment by troy379** [comment] 2017-05-03 14:52
unfortunately, i cannot reproduce this NPE, so I need your help.
please, update the version in your gradle dependency to `2.1` and show a new error log to let me understand where the problem exactly is.
thanks.

**Comment by DanteAndroid** [comment] 2017-05-04 01:01
![image](https://cloud.githubusercontent.com/assets/10005563/25687338/2a2efa40-30a8-11e7-9e86-a87e1eee7f8f.png)
Well, after updated it works surprisingly well... 
Besides, the `day` seems not displayed. Which in Chinese is x月x`日`

**Comment by DanteAndroid** [comment] 2017-05-04 03:13
One more problem: 
Exception when long click on message:
```
 java.lang.StringIndexOutOfBoundsException: length=0; regionStart=-2; regionLength=2
                                                                   at java.lang.AbstractStringBuilder.startEndAndLength(AbstractStringBuilder.java:211)
                                                                   at java.lang.AbstractStringBuilder.replace0(AbstractStringBuilder.java:437)
                                                                   at java.lang.StringBuilder.replace(StringBuilder.java:637)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.a(SourceFile:569)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.a(SourceFile:322)
                                                                   at com.dante.diary.chat.ConversationActivity.b(SourceFile:65)
                                                                   at com.dante.diary.chat.ConversationActivity.a(SourceFile)
                                                                   at com.dante.diary.chat.ConversationActivity$$Lambda$2.a(Unknown Source)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.e(SourceFile:492)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.b(SourceFile:341)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.a(SourceFile:324)
                                                                   at com.dante.diary.chat.ConversationActivity.b(SourceFile:65)
                                                                   at com.dante.diary.chat.ConversationActivity.a(SourceFile)
                                                                   at com.dante.diary.chat.ConversationActivity$$Lambda$2.a(Unknown Source)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.e(SourceFile:492)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.c(SourceFile:480)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter.b(SourceFile:46)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter$1.onClick(SourceFile:527)
                                                                   at android.view.View.performClick(View.java:5697)
                                                                   at com.stfalcon.chatkit.messages.MessagesListAdapter$2.onLongClick(SourceFile:550)
                                                                   at android.view.View.performLongClick(View.java:5736)
                                                                   at android.view.View$CheckForLongPress.run(View.java:22500)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:158)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
Code:
```
        adapter.enableSelectionMode(count -> adapter.copySelectedMessagesText(ConversationActivity.this, Message::getText, false));
        messagesList.setAdapter(adapter);
```
Thx!

**Comment by mradzinski** [comment] 2017-05-07 07:01
Would you mind disabling the code minification? just set `minifyEnabled` to false. It's kind of impossible to go through a minified stack trace. 

In regards to the NPE: That's an issue with your project setup. `com.stfalcon.chatkit` package doesn't show up anywhere in there, so I must assume that it was either a gradle version issue or a forced outdated compat library.

Now, the long click stack trace:
1- What's the reported length of the message your are trying to copy? Is it longer than 2 UTF-8 chars? That error is telling you in the very first line that `length=0`.
2- `Message::getText`? The signature for that method is `copySelectedMessagesText(Context, Formatter<MESSAGE>, boolean)`. You are supposed to provide a class that implements the `Formatter` interface, not a String.

**Comment by DanteAndroid** [comment] 2017-05-08 02:06
Long click issue:
1. the length is longer than 2, but should be able to be copied.
2. it's lambda, represents:
```
 adapter.enableSelectionMode(count -> adapter.copySelectedMessagesText(ConversationActivity.this, new MessagesListAdapter.Formatter<Message>() {
            @Override
            public String format(Message message) {
                return message.getText();
            }
        }, false));
```
Thx again! I'll turn off `minify` then come back!

**Comment by mradzinski** [comment] 2017-05-08 02:53
I just tried copying multiple different texts in English, Chinese and Arab (just checking if it might be an issue with the locale of the text) without having any issues at all. I even tried to create a ```StringIndexOutOfBoundsException``` by passing an empty string to no avail. All of this makes me think if it's not actually an issue with your proguard configuration rather and the implementation of the library itself. You were minifying your project, so maybe you were leaving out some needed classes/methods by mistake.

**Comment by DanteAndroid** [comment] 2017-05-08 06:19
@mradzinski So what should I add to proguard, thx!

**Comment by mradzinski** [comment] 2017-05-08 06:22
Did you try disabling minification and it worked? If so then as I said it's your proguard configuration causing issues. If it worked without minification then share your proguard file and we'll see what we can do.

**Comment by DanteAndroid** [comment] 2017-05-08 07:07
Sadly, it still crashes:
```
 Process: com.dante.diary, PID: 24056
                                                                 java.lang.StringIndexOutOfBoundsException: length=0; regionStart=-2; regionLength=2
                                                                     at java.lang.AbstractStringBuilder.startEndAndLength(AbstractStringBuilder.java:211)
                                                                     at java.lang.AbstractStringBuilder.replace0(AbstractStringBuilder.java:437)
                                                                     at java.lang.StringBuilder.replace(StringBuilder.java:637)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.getSelectedText(MessagesListAdapter.java:569)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.copySelectedMessagesText(MessagesListAdapter.java:322)
                                                                     at com.dante.diary.chat.ConversationActivity$1.onSelectionChanged(ConversationActivity.java:95)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.notifySelectionChanged(MessagesListAdapter.java:492)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.unselectAllItems(MessagesListAdapter.java:341)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.copySelectedMessagesText(MessagesListAdapter.java:324)
                                                                     at com.dante.diary.chat.ConversationActivity$1.onSelectionChanged(ConversationActivity.java:95)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.notifySelectionChanged(MessagesListAdapter.java:492)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.incrementSelectedItemsCount(MessagesListAdapter.java:480)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter.access$100(MessagesListAdapter.java:46)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter$1.onClick(MessagesListAdapter.java:527)
                                                                     at android.view.View.performClick(View.java:5697)
                                                                     at com.stfalcon.chatkit.messages.MessagesListAdapter$2.onLongClick(MessagesListAdapter.java:550)
                                                                     at android.view.View.performLongClick(View.java:5736)
                                                                     at android.view.View$CheckForLongPress.run(View.java:22500)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

Code:
```
 adapter = new MessagesListAdapter<>(otherId, (imageView, url) -> Glide.with(ConversationActivity.this)
                .load(url)
                .into(imageView));
//        adapter.setOnMessageLongClickListener(message -> {
//            adapter.copySelectedMessagesText(ConversationActivity.this, Message::getText, false);
//            UiUtils.showSnack(messagesList, R.string.copyed);
//        });
        adapter.enableSelectionMode(new MessagesListAdapter.SelectionListener() {
            @Override
            public void onSelectionChanged(int count) {
                adapter.copySelectedMessagesText(ConversationActivity.this, message -> message.getText(), false);
            }
        });
        messagesList.setAdapter(adapter);
```

**Comment by DanteAndroid** [comment] 2017-05-08 09:41
Beside, could you tell me why the date is not shown? And why all the messages are on one side even if the ids are different two.
```
          Message msg = new Message(message.getFrom(),
                    message.getText(), new Author(otherUser), new Date(message.getTimestamp()));
            messages.add(msg);
            Log.d(TAG, "fetchMessage: add message" + msg.toString());
            adapter.addToStart(msg, false);
```
Log:
```
 fetchMessage: add messageMessage{imageUrl='null', id='100676908', text='Aaaaaa', author=com.dante.diary.chat.Author@b504bc5, createdAt=Fri May 05 15:31:10 GMT+08:00 2017}

05-08 17:38:08.176 17332-17332/com.dante.diary D/GifHeaderParser: Author: User{id=100676908, name='DanteTest', intro='null', created='Wed May 03 16:52:15 GMT+08:00 2017', state=1, avatarUrl='http://s.timepill.net/user_icon/20135/s100676908.jpg?v=0'}

05-08 17:38:08.176 17332-17332/com.dante.diary D/PMActivity: fetchMessage: add messageMessage{imageUrl='null', id='100158434', text='high', author=com.dante.diary.chat.Author@7a4791a, createdAt=Fri May 05 15:46:00 GMT+08:00 2017}
```

**Comment by DanteAndroid** [comment] 2017-05-09 04:04
![image](https://cloud.githubusercontent.com/assets/10005563/25835198/5ab15c2a-34af-11e7-9bab-43fb5cc2bb8d.png)
Could you tell me why the other user's avatar is not shown(which I think should be reversed, me should be on the left and avatar be gone, another user on the right and avatar should be shown)?

**Comment by DanteAndroid** [comment] 2017-05-09 07:02
@mradzinski When I was writing the demo, I suddenly found the answer in:
```
adapter = new MessagesListAdapter<>(otherId, (imageView, url) -> Glide.with(ConversationActivity.this)
                .load(url)
                .into(imageView));
```
Yea, I mistaken the constructor param of MessagesListAdapter. 
I'd be happy if you mention that param. Of course, it's my problem.
Here is a demo for LongClick crash problem:
[app.zip](https://github.com/stfalcon-studio/ChatKit/files/985783/app.zip)

Thanks!

**Comment by mradzinski** [comment] 2017-05-09 07:36
The issues is a race condition in between two threads. You are implementing `adapter.copySelectedMessagesText` inside the `onSelectionChanged` listener while `copySelectedMessagesText` clearly specifies in it's documentation that it will unselect all messages for you.

Here's the demo working:
[app.zip](https://github.com/stfalcon-studio/ChatKit/files/985844/app.zip)

**Comment by DanteAndroid** [comment] 2017-05-09 08:23
Thx!
One last question:
How to set empty view when message list is empty(like a textView says "No message")?Didn't find it on doc!

**Comment by mradzinski** [comment] 2017-05-09 08:27
Well, that's totally in your hands. There's no implemented way of doing it and for good reason: It'll totally depend on why there's no messages (an error maybe? lack of users in the chat? who knows.), also, an empty state message should not be imposed but designed to meet your application.

By the time you access a chat you should retrieve an array of messages from somewhere, so if that array count is 0 you should (or shouldn't, totally up to you) display a message.

**Comment by troy379** [comment] 2017-06-29 14:21
@mradzinski thank you for help! I'm closing the issue.

**Closed by troy379** 2017-06-29 14:21 UTC
